version: "3.8"
services:
  api-server:
    image: azbuilder/api-server:latest
    container_name: api-server
    environment:
      - AzureAdAppId=
      - AzureAdApiIdUri=api://azbuilder
      - ApiDataSourceType=H2
    ports:
      - 8080:8080
    networks:
      - azbuilder-backend
    restart: unless-stopped
  api-job:
    image: azbuilder/api-job:latest
    container_name: api-job
    environment:
      - AzBuilderApiUrl=http://api-server:8080
      - AzureAdAppClientId=
      - AzureAdAppClientSecret=
      - AzureAdAppTenantId=
      - AzureAdAppScope=api://azbuilder/.default
      - AzBuilderExecutorUrl=http://executor:8090/api/v1/terraform-rs
    depends_on:
      - api-server
      - executor
    ports:
      - 8085:8085
    networks:
      - azbuilder-backend
    restart: unless-stopped
  executor:
    image: azbuilder/executor:latest
    container_name: executor
    environment:
      - TerraformStateType=AzureTerraformStateImpl
      - AzureTerraformStateResourceGroup=
      - AzureTerraformStateStorageAccountName=
      - AzureTerraformStateStorageContainerName=tfstate
      - AzureTerraformStateStorageAccessKey=
      - TerraformOutputType=AzureTerraformOutputImpl
      - AzureTerraformOutputAccountName=
      - AzureTerraformOutputAccountKey=
      - AzBuilderApiUrl=http://api-server:8080
      - AzureAdAppClientId=
      - AzureAdAppClientSecret=
      - AzureAdAppTenantId=
      - AzureAdAppScope=api://azbuilder/.default
      - ExecutorFlagBatch=false
      - ExecutorFlagDisableAcknowledge=false
    ports:
      - 8090:8090
    networks:
      - azbuilder-backend
    restart: unless-stopped
networks:
  azbuilder-backend:
    name: azbuilder-backend
    ipam:
      driver: default
      config:
        - subnet: "172.30.0.0/24"
  
